title: Alessandro Sebastianelli
email: alessandro.sebastianelli@gmail.com
description: Ph.D. student at University of Sannio and ESA under OSIP contract
show_downloads: false

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

- title: Home
  url: /

- title: Group of Things
  url: /group/
  sublinks:
    - title: Sub-item 1
      url: /group/si1
    - title: Sub-item 2
      url: /group/si2
    - title: Sub-item 3
      url: /group/si3